<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>VLFLib</PackageId>
    <Authors>Cra0</Authors>
    <Company>Cra0Digital</Company>
    <Description>Helper library for dealing with VLF signals.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>rf; vlf; gks</PackageTags>
    

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/cra0/Gatekeeper-Systems-SmartWheel</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/cra0/Gatekeeper-Systems-SmartWheel</PackageProjectUrl>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>

    <Version>0.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup> 

</Project>
